Akala/urls.py
from django.urls import path
from . import views
from .views import line_chart_json

app_name = 'Akala'

urlpatterns = [
    path('', views.product_all, name='product_all'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('store/<slug:category_slug>/', views.category_list, name='category_list'),

    path('login/', views.login_view, name='login_user'),
    path('seller_signup/', views.seller_signup, name='seller_signup'),
    path('logoutseller/', views.logoutSeller, name='logout_seller'),

    path('edit_product/<slug:slug>/', views.edit_product, name='edit_product'),
    path('delete_product/<slug:slug>/', views.delete_product, name='delete_product'),
    path('user_page/', views.user_page, name='user_page'),

    path('basket_show/', views.basket_show, name='basket_show'),
    path('delete_basket_product/<slug:slug>/', views.delete_basket_product, name='delete_basket_product'),
    path('basket_delete_all/', views.basket_delete_all, name='basket_delete_all'),
    path('buy_basket/', views.buy_basket, name='buy_basket'),

    # path('chart/', line_chart, name='line_chart'),
    path('chartJSON/<slug:slug>', line_chart_json, name='line_chart_json'),

    # path('test/', views.LineChartJSONView.as_view, name='test')
]

armin_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Akala.urls', namespace='Akala')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html lang="">

<head>
    <meta charset="utf-8"/>
    <title>{% block title %}My shop{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href='/static/css/bootstrap.css' rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"
            integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
    <script src="/static/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    <script src='/static/js/bootstrap.js'></script>
    <link href="/static/font-awesome/css/font-awesome.min.css" rel="stylesheet">

    <link href="/static/css/animate.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">

    <style>
        .example {
            color: #0a568c;
        }

        .navbar-nav .nav-link {
            transition: color 0.3s ease;
        }
        
        .navbar-nav .nav-link:hover {
            color: #0d6efd; /* Bootstrap Primary Color */
        }
        
        .dropdown-menu .dropdown-item:hover {
            background-color: #f8f9fa;
        }
        
        .btn-outline-primary {
            border: 2px solid #0d6efd;
            transition: all 0.3s ease;
        }
        
        .btn-outline-primary:hover {
            background-color: #0d6efd;
            color: #fff;
        }
        
    </style>

</head>

<body>
<header>
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm sticky-top">
        <div class="container-fluid">
            <a class="navbar-brand fw-bold" href="/">Akala</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'user_page' %}active{% endif %}" href="{% url "Akala:user_page" %}">
                            <i class="bi bi-person-circle me-1"></i> Seller Profile
                        </a>
                    </li>
                    
                    {% if not request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "Akala:login_user" %}">
                                <i class="bi bi-box-arrow-in-right me-1"></i> Seller Login
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "Akala:seller_signup" %}">
                                <i class="bi bi-person-plus me-1"></i> Seller Sign Up
                            </a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link text-danger" href="{% url "Akala:logout_seller" %}">
                                <i class="bi bi-box-arrow-left me-1"></i> Logout
                            </a>
                        </li>
                    {% endif %}
    
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-book me-1"></i> Library
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url "Akala:product_all" %}">All</a></li>
                            {% for c in categories %}
                                <li>
                                    <a class="dropdown-item {% if category.slug == c.slug %}active{% endif %}" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
                
                <a href="{% url "Akala:basket_show" %}" class="btn btn-outline-primary d-flex align-items-center">
                    <i class="bi bi-cart me-2"></i>
                    Basket
                </a>
            </div>
        </div>
    </nav>
    
</header>
<div id="content">{% block content %} {% endblock %}</div>
</body>
</html>

templates/store/edit_product.html
{% extends "base.html" %}
{% load static %}
{% block title %}SELLER PAGE{% endblock %}
{% block content %}

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
    </head>
    <body>
    <h2>
        all the products listed by {{ seller.name }}
    </h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit" name="Edit">
            Edit
        </button>

    </form>
    </body>
    </html>
{% endblock %}

templates/store/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}


    <main>

        <section class="py-5 text-center container">
            <div class="row py-lg-4">
                <div class="col-lg-6 col-md-8 mx-auto">
                    <h1 class="h1 fw-bold text-white">EXPLORE, SELECT, BUY</h1>
                    <p class="lead text-white">from office requirements all the way to furniture, what you search for is
                        few clicks away</p>
                    <p>
                        <a href="{% url 'Akala:seller_signup' %}" class="btn btn-primary my-2">Make an account</a>
                    </p>
                </div>
            </div>
        </section>

        <div class="album py-5 bg-light">
            <div class="container">

                <div class="pb-3 h5">All items</div>
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

                    {% for product in products %}

                        <div class="col">
                            <div class="card shadow-sm">
                                <img class="img-fluid" alt="Responsive image" {% if product.image %}
                                     src="{{ product.image.url }}" {% else %}
                                     src="{% static "images/f362733f-f3fc-4c8f-9c7f-4f5e6ae47feb.png" %}"{% endif %}>
                                <div class="card-body">
                                    <p class="card-text">
                                        <a class="text-dark text-decoration-none"
                                           href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                                    </p>
                                    <div class="d-flex justify-content-between align-items-center">

                                        <small class="text-muted">{% if product.is_discount == True %}
                                            <s style="color: #808080">${{ product.price }}</s>
                                            <br>
                                            <font size="+2"
                                                  style="color: #000000"><strong>${{ product.discounted_price }}</strong></font>
                                        {% else %}<font size="+2"> ${{ product.price }}{% endif %}</font></small>
                                    </div>

                                </div>
                            </div>
                        </div>

                    {% endfor %}

                </div>
            </div>
        </div>
    </main>

{% endblock %}

templates/store/seller_login.html
{% extends "base.html" %}
{% load static %}
{% block title %}LOGIN{% endblock %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/super_blue.css' %}">
    <div class="login-box-wrapper">
        <div class="login-box" style="top: 200px !important;">
            <h2>Login</h2>
            <form method="post" id="loginForm">
                <label>username</label>
                <div class="user-box">
                    {{ form.username }}
                </div>
                <label>password</label>
                <div class="user-box">
                    {{ form.password }}
                </div>
                {% csrf_token %}

                <a style="color: #fff" onclick="document.getElementById('loginForm').submit();">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                    Login
                </a>
                <a href="{% url "Akala:seller_signup" %}">Don't have an account?</a>
            </form>
        </div>
    </div>
    {% if error_message != "" %}
    <script>
        alert('{{ error_message }}');
    </script>
{% endif %}
{% endblock %}

templates/store/seller_sign.html
{% extends "base.html" %}
{% load static %}
{% block title %}SIGN UP{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/super_blue.css' %}">
    <div class="login-box" style="top: 300px !important;">
        <h2>Sign up</h2>
        <form method="post" id="signupForm">
            <label>username</label>
            <div class="user-box">
                {{ form.username }}
            </div>
            <label>email</label>
            <div class="user-box">
                {{ form.email }}
            </div>
            <label>password</label>
            <div class="user-box">
                {{ form.password1 }}
            </div>
            <label>confirm password</label>
            <div class="user-box">
                {{ form.password2 }}
            </div>
            {% csrf_token %}

            <a style="color: #fff" onclick="document.getElementById('signupForm').submit();">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                Login
            </a>
            <a href="{% url "Akala:login_user" %}">already have an account?</a>
        </form>
    </div>
{% endblock %}

templates/store/test.html
{% load static %}

<!DOCTYPE html>
<html lang="">
<head>
    <title>django-chartjs line chart demo</title>
    <!--[if lte IE 8]>
                <script src="{% static 'js/excanvas.js' %}"></script>
            <![endif]-->
</head>
<body>
<h1>Price chart</h1>

<canvas id="myChart" style="position: fixed" width="50%" height="50%"></canvas>

<script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
<script type="text/javascript" src="{% static 'js/Chart.min.js' %}"></script>
<script type="text/javascript">
    $.get('{% url "Akala:line_chart_json" %}', function (data) {
        var ctx = $("#myChart").get(0).getContext("2d");
        new Chart(ctx, {
            type: 'line', data: data
        });
    });
</script>
</body>
</html>