Akala/urls.py
from django.urls import path
from . import views
from .views import line_chart_json

app_name = 'Akala'

urlpatterns = [
    path('', views.product_all, name='product_all'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('store/<slug:category_slug>/', views.category_list, name='category_list'),

    path('login/', views.login_view, name='login_user'),
    path('seller_signup/', views.seller_signup, name='seller_signup'),
    path('logoutseller/', views.logoutSeller, name='logout_seller'),

    path('edit_product/<slug:slug>/', views.edit_product, name='edit_product'),
    path('delete_product/<slug:slug>/', views.delete_product, name='delete_product'),
    path('user_page/', views.user_page, name='user_page'),

    path('basket_show/', views.basket_show, name='basket_show'),
    path('delete_basket_product/<slug:slug>/', views.delete_basket_product, name='delete_basket_product'),
    path('basket_delete_all/', views.basket_delete_all, name='basket_delete_all'),
    path('buy_basket/', views.buy_basket, name='buy_basket'),

    # path('chart/', line_chart, name='line_chart'),
    path('chartJSON/<slug:slug>', line_chart_json, name='line_chart_json'),

    # path('test/', views.LineChartJSONView.as_view, name='test')
]

armin_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Akala.urls', namespace='Akala')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/store/products/basket.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link href="/static/font-awesome/css/font-awesome.css" rel="stylesheet">

        <link href="/static/css/animate.css" rel="stylesheet">
        <link href="/static/css/style.css" rel="stylesheet">
        <title> My Basket </title>

    </head>

    <div class="main-content" style="margin-left: 20px; margin-right: 20px;">

        <br>
        <div style="color: whitesmoke" class="pb-3 h3">Its MR.{{ user }}'s Basket</div>

        {% if products.count != 0 %}
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

            {% for product in products %}

                <div class="col">
                    <div class="card shadow-sm">
                        <img class="img-fluid" alt="Responsive image" {% if product.image %}
                             src="{{ product.image.url }}" {% else %}
                             src="{% static "images/f362733f-f3fc-4c8f-9c7f-4f5e6ae47feb.png" %}"{% endif %}>
                        <div class="card-body">
                            <p class="card-text">
                                <a class="text-dark text-decoration-none"
                                   href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                            </p>
                            <div class="d-flex justify-content-between align-items-center">

                                <small class="text-muted">{% if product.is_discount == True %}
                                    <s style="color: #808080">${{ product.price }}</s>
                                    <br>
                                    <font size="+2"
                                          style="color: #000000"><strong>${{ product.discounted_price }}</strong></font>
                                {% else %}<font size="+2"> ${{ product.price }}{% endif %}</font></small>
                            </div>
                            <a href="{% url "Akala:delete_basket_product" slug=product.slug %}"
                               class="btn btn-danger m-1">DElETE
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h2>go and buy some products {{ user }}</h2>
        {% endif %}

        </div>

        <br>
        <div class="col-md-3">

            <div class="ibox">
                <div class="ibox-title">
                    <h5>Cart Summary</h5>
                </div>
                <div class="ibox-content">
                            <span>
                                Total
                            </span>


                    <h2 class="font-bold">
                        ${{ total_price }}
                    </h2>


                    <hr/>
                    <span class="text-muted small">
                                *For United States, France and Germany applicable sales tax will be applied
                            </span>
                    <div class="m-t-sm">
                        <div class="btn-group">
                            <a href="{% url "Akala:buy_basket" %}" class="btn btn-primary btn-sm"><i
                                    class="fa fa-shopping-cart"></i> BUY EM ALL</a>
                            <a href="{% url "Akala:basket_delete_all" %}"
                               class="btn btn-white btn-sm"> Cancel</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="ibox">
                <div class="ibox-title">
                    <h5>Support</h5>
                </div>
                <div class="ibox-content text-center">


                    <h3><i class="fa fa-phone"></i> +0936 78 48 199</h3>
                    <span class="small">
                                Please contact with us if you have any questions. We are available 24h.
                </span>


                </div>
            </div>


        </div>
    </div>
    <br>

    <!-- Mainly scripts -->
    <script src="/static/js/jquery-3.1.1.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="/static/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

    <!-- Custom and plugin javascript -->
    <script src="/static/js/inspinia.js"></script>
    <script src="/static/js/plugins/pace/pace.min.js"></script>
{% endblock %}

templates/store/products/category.html
{% extends "base.html" %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}


<main>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">{{category.name|title}}</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for product in products %}

        <div class="col">
          <div class="card shadow-sm">
            <img class="img-fluid" alt="Responsive image" {% if product.image %} src="{{ product.image.url }}" {% else %} src="{% static "images/f362733f-f3fc-4c8f-9c7f-4f5e6ae47feb.png" %}"{% endif %}>
            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.name }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">{% if product.is_discount == True %}
                    <s style="color: #808080">${{ product.price }}</s>
                    <br>
                    <font size="+2" style="color: #000000"><strong>${{ product.discounted_price }}</strong></font>
                {% else %}<font size="+2">${{ product.price }}{% endif %}</font></small>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>
</main>

{% endblock %}

templates/store/products/single.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    {{ product.name }}
{% endblock %}
{% block content %}
    <div class="container" style="background-color:powderblue;">
        <main class="pt-5">
            <div class="row g-3 p-4">
                <div class="col-md-5 col-lg-5 order-md-first bg-light">
                    <img class="img-fluid mx-auto d-block p-4 " width="200px" alt="Responsive image" {% if product.image %}
                         src="{{ product.image.url }}" {% else %}
                         src="{% static "images/f362733f-f3fc-4c8f-9c7f-4f5e6ae47feb.png" %}"{% endif %}>
                    <br>

                    {% if my_price %}
                        <h2>Price chart</h2>
                        <div>
                        </div>
                        <div>

                        <canvas id="myChart" width="50%" height="50%"></canvas>
                        </div>
                        <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
                        <script type="text/javascript" src="{% static 'js/Chart.min.js' %}"></script>
                        <script type="text/javascript">
                            $.get('{% url "Akala:line_chart_json" slug=product.slug %}', function (data) {
                                var ctx = $("#myChart").get(0).getContext("2d");
                                new Chart(ctx, {
                                    type: 'line', data: data
                                });
                            });
                        </script>
                        {{ chart }}

                    {% else %}
                        <h2>
                            this product doesn't have any data
                        </h2>
                    {% endif %}
                    <br>

                </div>

                <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                    <h1 class="mb-0 h4">{{ product.name }}</h1>
                    <strong><p>available on: <span class="lead">{{ Seller.name }}</span> {{ product.created_by }}</p>
                    </strong>
                    <p>{{ product.description|slice:":355" }}...</p>
                    <div class="border">
                        <div class="col border-bottom">
                            <div class="row p-3">
                                <div class="col-6"><font size="+3">price</font></div>
                                <div class="col-6 text-end"><span
                                        class="h4 fw-bold">{% if product.is_discount == True %}
                                    <s style="color: #808080">${{ product.price }}</s>
                                    <br>
                                    <font size="+2"
                                          style="color: #000000"><strong>${{ product.discounted_price }}</strong></font>
                                {% else %}${{ product.price }}{% endif %}</span></div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="row p-3">
                                <div class="col-6">
                                    <label for="select">Quantity</label>
                                    <select id="select" name="quantity">
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                        <option value="4">4</option>
                                    </select>
                                </div>
                                <div class="col-6 text-end">
                                    <form method="POST" action="{% url 'Akala:product_detail' product.slug %}">
                                        {% csrf_token %}
                                        <button name="add_to_basket" type="submit" id="add-button"
                                                class="btn btn-secondary btn-sm">Add to
                                            basket
                                        </button>
                                    </form>
                                </div>
                                <div class="col-md-12">
                                    {% with comments as total_comments %}
                                        <h2>
                                            comment{{ total_comments|pluralize }}
                                        </h2>
                                    {% endwith %}
                                    {% for comment in comments %}
                                        Comment by {{ comment.name }}
                                        on {{ comment.publish }}
                                        {{ comment.content|linebreaks }}
                                    {% empty %}
                                        <p>there are no comments ...yet</p>
                                    {% endfor %}
                                    <h2>make a new comment</h2>
                                    <form id="form" method="post">
                                        <div class="form-outline mb-4">

                                            <label class="form-label" for="form2Example1">name</label>
                                            {{ comment_form.name }}
                                        </div>
                                        <div class="form-outline mb-4">
                                            <label class="form-label" for="form2Example1">email</label>
                                        </div>
                                        {{ comment_form.email }}
                                        <div class="form-outline mb-4">
                                            <label class="form-label" for="form2Example1">content</label>

                                            {{ comment_form.content }}
                                        </div>
                                        {% csrf_token %}
                                        <button name="add_comment" type="submit"
                                                class="btn-primary btn-lg btn-block">
                                            Submit
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
{% endblock %}